# Generated by Django 5.0.1 on 2024-01-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("title", "description")},
        ),
    ]
