# Generated by Django 5.0.1 on 2024-01-29 16:09

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.profile_picture_file_path
            ),
        ),
    ]
