# Generated by Django 5.0.1 on 2024-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_alter_profile_bio_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
