# Generated by Django 5.0.1 on 2024-01-31 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_following",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_following_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
