# Generated by Django 5.0.1 on 2024-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0011_profile_follow_profile_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.CharField(
                choices=[(1, "Follow"), (2, "Unfollow")], max_length=1
            ),
        ),
    ]
