# Generated by Django 5.0.1 on 2024-02-01 12:02

import social.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0012_alter_profile_follow"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.post_picture_file_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.CharField(
                choices=[("F", "Follow"), ("U", "Unfollow")], max_length=1
            ),
        ),
    ]
