# Generated by Django 5.0.1 on 2024-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_post_hashtags_post_image_alter_profile_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="follow",
            field=models.CharField(
                blank=True,
                choices=[("F", "Follow"), ("U", "Unfollow")],
                max_length=1,
                null=True,
            ),
        ),
    ]
