# Generated by Django 5.0.1 on 2024-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0015_alter_post_follow_comment_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="replies",
            field=models.ManyToManyField(blank=True, to="social.comment"),
        ),
    ]
