# Generated by Django 5.0.1 on 2024-02-09 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_comment_replies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.CharField(
                choices=[("L", "Like"), ("D", "Dislike"), ("U", "Unlike")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="i_like",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="social.post"
            ),
        ),
    ]
