# Generated by Django 4.2.10 on 2024-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_post_like_post_liked_by_profile_i_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="i_like",
            field=models.ManyToManyField(
                blank=True, related_name="posts_i_like", to="social.post"
            ),
        ),
    ]
