# Generated by Django 4.2.10 on 2024-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0018_alter_profile_i_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.CharField(
                blank=True, choices=[("F", "Follow"), ("U", "Unfollow")], max_length=1
            ),
        ),
    ]
