# Generated by Django 4.2.10 on 2024-02-16 13:17

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0020_alter_post_hashtags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["post", "user", "id"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["user", "id"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=social.models.post_picture_file_path,
            ),
        ),
    ]
