# Generated by Django 4.2.10 on 2024-02-17 18:22

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0021_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="replies",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.post_picture_file_path
            ),
        ),
    ]
